table 'Data Dictionary'
	isHidden
	lineageTag: cd632df2-0c9c-48cb-baed-55c58cff8daf

	column Table
		dataType: string
		isHidden
		lineageTag: 378da311-17cc-44ba-9570-e9ce4359048a
		summarizeBy: none
		sourceColumn: Table

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column
		dataType: string
		isHidden
		lineageTag: 0e8aafc5-6bf6-423c-aecc-52c31037eb76
		summarizeBy: none
		sourceColumn: Column

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Example
		dataType: string
		isHidden
		lineageTag: fff739a7-90ae-4570-ac9e-40fa6c0181dd
		summarizeBy: none
		sourceColumn: Example

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Meaning (plain English)'
		dataType: string
		isHidden
		lineageTag: 14e3254a-5e87-48a2-a037-182a47c66c69
		summarizeBy: none
		sourceColumn: Meaning (plain English)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column5
		dataType: string
		isHidden
		lineageTag: b098d76b-32da-424b-865b-b9b1a290ee68
		summarizeBy: none
		sourceColumn: Column5

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column6
		dataType: string
		isHidden
		lineageTag: 936ac9ba-1da1-48bd-a291-037f13eef78a
		summarizeBy: none
		sourceColumn: Column6

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column7
		dataType: string
		isHidden
		lineageTag: 8fb7cffa-986d-4a55-897c-f8d672515610
		summarizeBy: none
		sourceColumn: Column7

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column8
		dataType: string
		isHidden
		lineageTag: 4f5c82f1-2ae3-4ec5-a2c0-250332017c85
		summarizeBy: none
		sourceColumn: Column8

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column9
		dataType: string
		isHidden
		lineageTag: f39f12f3-8d67-4463-b018-de1f41ceef70
		summarizeBy: none
		sourceColumn: Column9

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column10
		dataType: string
		isHidden
		lineageTag: 745a38c1-de3e-4024-8ce9-db9fb08ada1e
		summarizeBy: none
		sourceColumn: Column10

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column11
		dataType: string
		isHidden
		lineageTag: 21bc6a03-55c9-47e3-adb3-c93df499209d
		summarizeBy: none
		sourceColumn: Column11

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Data Dictionary' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\marco\OneDrive\Documentos\Repositorios\Git\Analytics\OnyxData\2026.01\data\Pharmacy_Data_Challenge_Dataset.xlsx"), null, true),
				    #"Data Dictionary_Sheet" = Fonte{[Item="Data Dictionary",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Data Dictionary_Sheet", [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Table", type text}, {"Column", type text}, {"Example", type any}, {"Meaning (plain English)", type text}, {"Column5", type any}, {"Column6", type any}, {"Column7", type any}, {"Column8", type any}, {"Column9", type any}, {"Column10", type any}, {"Column11", type text}})
				in
				    #"Tipo Alterado"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

