table DimPharmacy
	lineageTag: 4cd225f9-b512-49ac-9fd2-70a6fabbb4f5

	column PharmacyID
		dataType: string
		lineageTag: c3f9a6d0-c50d-4a3b-b847-3f9d81f60cd6
		summarizeBy: none
		sourceColumn: PharmacyID

		annotation SummarizationSetBy = Automatic

	column PharmacyName
		dataType: string
		lineageTag: ec5d68a4-86dc-47da-a39a-3dd43eab680e
		summarizeBy: none
		sourceColumn: PharmacyName

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: fd8b3384-a8c0-4b61-8900-a4826d5d3633
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 4fa0ff67-6db9-4f69-a28b-38520df4be1d
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 07afe3a6-96f6-406e-8531-f46ce3c32cf5
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column PharmacyType
		dataType: string
		lineageTag: 4ed6dd45-d563-445d-9f80-b7afc21a738b
		summarizeBy: none
		sourceColumn: PharmacyType

		annotation SummarizationSetBy = Automatic

	column OpenDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 1ec491f3-c749-4477-9817-09e7117c75cd
		summarizeBy: none
		sourceColumn: OpenDate

		variation Variation
			isDefault
			relationship: 3e9f39bc-e470-4d8e-bccb-b9f3eaf9ab63
			defaultHierarchy: LocalDateTable_73c650e9-1ff4-4ce1-9767-76fe22e45091.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column StoreSizeBand
		dataType: string
		lineageTag: 2f221089-a0d3-4274-bac6-9e0a88a258f2
		summarizeBy: none
		sourceColumn: StoreSizeBand

		annotation SummarizationSetBy = Automatic

	column Latitude
		dataType: double
		lineageTag: 1dd5b75b-aa5d-4af2-8d54-ad5e84b709ab
		summarizeBy: sum
		sourceColumn: Latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Longitude
		dataType: double
		lineageTag: 2281af8d-791a-4c2b-a1b2-8ff6297a8840
		summarizeBy: sum
		sourceColumn: Longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition DimPharmacy = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\marco\OneDrive\Documentos\Repositorios\Git\Analytics\OnyxData\2026.01\data\Pharmacy_Data_Challenge_Dataset.xlsx"), null, true),
				    DimPharmacy_Sheet = Fonte{[Item="DimPharmacy",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(DimPharmacy_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"PharmacyID", type text}, {"PharmacyName", type text}, {"Country", type text}, {"Region", type text}, {"City", type text}, {"PharmacyType", type text}, {"OpenDate", type date}, {"StoreSizeBand", type text}, {"Latitude", type number}, {"Longitude", type number}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

