table DimProduct
	lineageTag: 1f3858da-9757-466d-9e29-cbd199b70ad2

	column ProductID
		dataType: string
		lineageTag: 9f90047d-9ff1-4082-a29c-e5d163b2a44d
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: bd8072fc-b55e-4ae3-9874-09dc18f9efa4
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 4f860f96-a814-4b42-92a2-a466906fc779
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: d0ec77a1-cf2e-46cc-832c-ed59e59bf207
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column IsGeneric
		dataType: string
		lineageTag: bd9b6b54-81bf-4ac6-9744-6673e29710bf
		summarizeBy: none
		sourceColumn: IsGeneric

		annotation SummarizationSetBy = Automatic

	column PackSize
		dataType: string
		lineageTag: 47fdda6c-3461-4e77-89f1-83300f4938af
		summarizeBy: none
		sourceColumn: PackSize

		annotation SummarizationSetBy = Automatic

	column ListPriceEUR
		dataType: double
		lineageTag: 15ca390f-d43c-4ac8-af4b-13538d3c5f37
		summarizeBy: sum
		sourceColumn: ListPriceEUR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column StandardCostEUR
		dataType: double
		lineageTag: 6ca2e404-63c9-4547-b99c-2ede3fb3d998
		summarizeBy: sum
		sourceColumn: StandardCostEUR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LaunchDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 4a9b9509-a121-4430-87ef-76c6e943288a
		summarizeBy: none
		sourceColumn: LaunchDate

		variation Variation
			isDefault
			relationship: afbe1f70-bf33-4828-a415-ba33f61f60f7
			defaultHierarchy: LocalDateTable_4e0aaf73-e6b2-4a2b-89cb-b62cdaec83c3.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IsDiscontinued
		dataType: string
		lineageTag: 7197714d-9776-4251-b32a-687280a8ea71
		summarizeBy: none
		sourceColumn: IsDiscontinued

		annotation SummarizationSetBy = Automatic

	column DiscontinuedDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: a3bbb44b-d7c2-4ec8-bfb9-dfb8833afa26
		summarizeBy: none
		sourceColumn: DiscontinuedDate

		variation Variation
			isDefault
			relationship: f3eb26fe-c3bf-42ff-854c-5b7f2fbd2565
			defaultHierarchy: LocalDateTable_16e6932c-db99-4d18-a923-4ddbfd0ebded.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition DimProduct = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\marco\OneDrive\Documentos\Repositorios\Git\Analytics\OnyxData\2026.01\data\Pharmacy_Data_Challenge_Dataset.xlsx"), null, true),
				    DimProduct_Sheet = Fonte{[Item="DimProduct",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(DimProduct_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ProductID", type text}, {"ProductName", type text}, {"Category", type text}, {"Brand", type text}, {"IsGeneric", type text}, {"PackSize", type text}, {"ListPriceEUR", type number}, {"StandardCostEUR", type number}, {"LaunchDate", type date}, {"IsDiscontinued", type text}, {"DiscontinuedDate", type date}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

