table FactSales
	lineageTag: 6adf2ec6-7493-4b5e-9934-68d1714ee051

	column SalesID
		dataType: string
		lineageTag: 3c3f95e4-79a4-4ac6-8865-a1291ecad09d
		summarizeBy: none
		sourceColumn: SalesID

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 930edcc5-a058-4c87-a6e5-67e366174a8b
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column PharmacyID
		dataType: string
		lineageTag: 5d63ebd8-4cef-45e6-baa1-4c5c491a824f
		summarizeBy: none
		sourceColumn: PharmacyID

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: string
		lineageTag: 624f0d01-a2ab-474b-b085-03b8d081adaa
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column UnitsSold
		dataType: int64
		formatString: 0
		lineageTag: 3683d994-c33e-46fa-8eeb-e55c04dbd2c3
		summarizeBy: sum
		sourceColumn: UnitsSold

		annotation SummarizationSetBy = Automatic

	column RevenueEUR
		dataType: double
		lineageTag: 153e8210-159e-4f19-9113-f76025a62191
		summarizeBy: sum
		sourceColumn: RevenueEUR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CostEUR
		dataType: double
		lineageTag: 31327284-ae72-4f8d-80e2-13e98e5bc2aa
		summarizeBy: sum
		sourceColumn: CostEUR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MarginEUR
		dataType: double
		lineageTag: 90a1398d-8236-4c13-93d3-06f7c916f6a1
		summarizeBy: sum
		sourceColumn: MarginEUR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PromoFlag
		dataType: string
		lineageTag: ab9a75ce-074c-4241-9f42-a2296eeae1e9
		summarizeBy: none
		sourceColumn: PromoFlag

		annotation SummarizationSetBy = Automatic

	partition FactSales = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\marco\OneDrive\Documentos\Repositorios\Git\Analytics\OnyxData\2026.01\data\Pharmacy_Data_Challenge_Dataset.xlsx"), null, true),
				    FactSales_Sheet = Fonte{[Item="FactSales",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(FactSales_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"SalesID", type text}, {"DateKey", Int64.Type}, {"PharmacyID", type text}, {"ProductID", type text}, {"UnitsSold", Int64.Type}, {"RevenueEUR", type number}, {"CostEUR", type number}, {"MarginEUR", type number}, {"PromoFlag", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

