{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.139.2054.0 (24.12)+334ca1c95b576cc53924655643b0d36f21caac55"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"dClientes\",\"dProdutos\",\"dVendedores\",\"fVendas\",\"dCalendario_Power Query\",\"_medidas\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {
          "content": {
            "Entities": {
              "dCalendario_Power_query": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario_Power Query"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "dCalendario_Power query": {
                      "State": "Generated"
                    }
                  },
                  {
                    "dcalendario_power enquiry": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "dcalendario_power inquiry": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "dcalendario_power interrogation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "dcalendario_power question": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "dcalendario_power request": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "dcalendario_power demand": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "dcalendario_power probe": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "dcalendario_power uncertainty": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "dcalendario_power reservation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "dcalendario_power objection": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "dCalendario_Power_query.ano": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario_Power Query",
                    "ConceptualProperty": "Ano"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ano": {
                      "State": "Generated"
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "dCalendario_Power_query.data": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario_Power Query",
                    "ConceptualProperty": "Data"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "data": {
                      "State": "Generated"
                    }
                  },
                  {
                    "information": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "fact": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "info": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "statistic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "document": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "figure": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "record": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "dCalendario_Power_query.data.ano": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario_Power Query",
                    "Hierarchy": "Hierarquia de datas",
                    "HierarchyLevel": "Ano",
                    "VariationSet": "Variation",
                    "VariationSource": "Data"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ano": {
                      "State": "Generated"
                    }
                  },
                  {
                    "data ano": {
                      "State": "Generated"
                    }
                  },
                  {
                    "information ano": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "fact ano": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "info ano": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "statistic ano": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "document ano": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "figure ano": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "record ano": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "dCalendario_Power_query.data.dia": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario_Power Query",
                    "Hierarchy": "Hierarquia de datas",
                    "HierarchyLevel": "Dia",
                    "VariationSet": "Variation",
                    "VariationSource": "Data"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "dia": {
                      "State": "Generated"
                    }
                  },
                  {
                    "data dia": {
                      "State": "Generated"
                    }
                  },
                  {
                    "information dia": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "fact dia": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "info dia": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "statistic dia": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "document dia": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "figure dia": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "record dia": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "dCalendario_Power_query.data.hierarquia_de_data": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario_Power Query",
                    "Hierarchy": "Hierarquia de datas",
                    "VariationSet": "Variation",
                    "VariationSource": "Data"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "hierarquia de data": {
                      "State": "Generated"
                    }
                  },
                  {
                    "hierarquia de information": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "hierarquia de fact": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "hierarquia de info": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "hierarquia de statistic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "hierarquia de document": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "hierarquia de figure": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "hierarquia de record": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "dCalendario_Power_query.data.mê": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario_Power Query",
                    "Hierarchy": "Hierarquia de datas",
                    "HierarchyLevel": "Mês",
                    "VariationSet": "Variation",
                    "VariationSource": "Data"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "mê": {
                      "State": "Generated"
                    }
                  },
                  {
                    "data mê": {
                      "State": "Generated"
                    }
                  },
                  {
                    "information mê": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "fact mê": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "info mê": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "statistic mê": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "document mê": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "figure mê": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "record mê": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "dCalendario_Power_query.data.trimestre": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario_Power Query",
                    "Hierarchy": "Hierarquia de datas",
                    "HierarchyLevel": "Trimestre",
                    "VariationSet": "Variation",
                    "VariationSource": "Data"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "trimestre": {
                      "State": "Generated"
                    }
                  },
                  {
                    "data trimestre": {
                      "State": "Generated"
                    }
                  },
                  {
                    "information trimestre": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "fact trimestre": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "info trimestre": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "statistic trimestre": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "document trimestre": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "figure trimestre": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "record trimestre": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "dCalendario_Power_query.dia_da_semana": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario_Power Query",
                    "ConceptualProperty": "Dia da Semana"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "dia da semana": {
                      "State": "Generated"
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "dCalendario_Power_query.mê": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario_Power Query",
                    "ConceptualProperty": "Mês"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "mê": {
                      "State": "Generated"
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "dCalendario_Power_query.número_do_dia_da_semana": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario_Power Query",
                    "ConceptualProperty": "Número do Dia da Semana"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "número do dia da semana": {
                      "State": "Generated"
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "dCalendario_Power_query.número_do_mê": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario_Power Query",
                    "ConceptualProperty": "Número do Mês"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "número do mê": {
                      "State": "Generated"
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "dCalendario_Power_query.trimestre": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario_Power Query",
                    "ConceptualProperty": "Trimestre"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "trimestre": {
                      "State": "Generated"
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "d_calendario": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "d calendario": {
                      "State": "Generated"
                    }
                  },
                  {
                    "dCalendario": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "d_calendario.ano": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "ConceptualProperty": "Ano"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ano": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_calendario.ano_mê": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "ConceptualProperty": "AnoMês"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ano mê": {
                      "State": "Generated"
                    }
                  },
                  {
                    "AnoMês": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "d_calendario.ano_mês_número": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "ConceptualProperty": "AnoMês_Número"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ano mês número": {
                      "State": "Generated"
                    }
                  },
                  {
                    "ano mê número": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.78
                    }
                  },
                  {
                    "AnoMês_Número": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "d_calendario.date": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "ConceptualProperty": "Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "date": {
                      "State": "Generated"
                    }
                  },
                  {
                    "moment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "period": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "d_calendario.date.ano": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "Hierarchy": "Hierarquia de datas",
                    "HierarchyLevel": "Ano",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ano": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date ano": {
                      "State": "Generated"
                    }
                  },
                  {
                    "moment ano": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period ano": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "d_calendario.date.dia": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "Hierarchy": "Hierarquia de datas",
                    "HierarchyLevel": "Dia",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "dia": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date dia": {
                      "State": "Generated"
                    }
                  },
                  {
                    "moment dia": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period dia": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "d_calendario.date.hierarquia_de_data": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "Hierarchy": "Hierarquia de datas",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "hierarquia de data": {
                      "State": "Generated"
                    }
                  },
                  {
                    "hierarquia de information": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "hierarquia de fact": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "hierarquia de info": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "hierarquia de statistic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "hierarquia de document": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "hierarquia de figure": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "hierarquia de record": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  }
                ]
              },
              "d_calendario.date.mê": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "Hierarchy": "Hierarquia de datas",
                    "HierarchyLevel": "Mês",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "mê": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date mê": {
                      "State": "Generated"
                    }
                  },
                  {
                    "moment mê": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period mê": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "d_calendario.date.trimestre": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "Hierarchy": "Hierarquia de datas",
                    "HierarchyLevel": "Trimestre",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "trimestre": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date trimestre": {
                      "State": "Generated"
                    }
                  },
                  {
                    "moment trimestre": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period trimestre": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "d_calendario.dia_da_semana": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "ConceptualProperty": "Dia da Semana"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "dia da semana": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_calendario.mê": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "ConceptualProperty": "Mês"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "mê": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_calendario.mês_ano": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "ConceptualProperty": "MêsAno"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "mês ano": {
                      "State": "Generated"
                    }
                  },
                  {
                    "mê ano": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.78
                    }
                  },
                  {
                    "MêsAno": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "Mês": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "d_calendario.número_do_dia_da_semana": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "ConceptualProperty": "Número do Dia da Semana"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "número do dia da semana": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_calendario.número_do_mê": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "ConceptualProperty": "Número do Mês"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "número do mê": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_calendario.trimestre": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "ConceptualProperty": "Trimestre"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "trimestre": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_cliente": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dClientes"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "d cliente": {
                      "State": "Generated"
                    }
                  },
                  {
                    "dClientes": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "d_cliente.ID_cliente": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dClientes",
                    "ConceptualProperty": "ID_Cliente"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ID cliente": {
                      "State": "Generated"
                    }
                  },
                  {
                    "ID_Cliente": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "identification cliente": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identity cliente": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identifier cliente": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "credential cliente": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "d_cliente.cidade": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dClientes",
                    "ConceptualProperty": "Cidade"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "cidade": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_cliente.estado": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dClientes",
                    "ConceptualProperty": "Estado"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "estado": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_cliente.idade": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dClientes",
                    "ConceptualProperty": "Idade"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "idade": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_cliente.nome_cliente": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dClientes",
                    "ConceptualProperty": "Nome_Cliente"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "nome cliente": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Nome_Cliente": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "d_produto": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dProdutos"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "d produto": {
                      "State": "Generated"
                    }
                  },
                  {
                    "dProdutos": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "d_produto.ID_produto": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dProdutos",
                    "ConceptualProperty": "ID_Produto"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ID produto": {
                      "State": "Generated"
                    }
                  },
                  {
                    "ID_Produto": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "identification produto": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identity produto": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identifier produto": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "credential produto": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "d_produto.categoria": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dProdutos",
                    "ConceptualProperty": "Categoria"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "categoria": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_produto.nome_produto": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dProdutos",
                    "ConceptualProperty": "Nome_Produto"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "nome produto": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Nome_Produto": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "d_produto.preco_unitario": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dProdutos",
                    "ConceptualProperty": "Preco_Unitario"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "preco unitario": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Preco_Unitario": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "d_vendedore": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dVendedores"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "d vendedore": {
                      "State": "Generated"
                    }
                  },
                  {
                    "dVendedores": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "d_vendedore.ID_vendedor": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dVendedores",
                    "ConceptualProperty": "ID_Vendedor"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ID vendedor": {
                      "State": "Generated"
                    }
                  },
                  {
                    "ID_Vendedor": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "identification vendedor": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identity vendedor": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identifier vendedor": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "credential vendedor": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "d_vendedore.comissao": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dVendedores",
                    "ConceptualProperty": "Comissao (%)"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "comissao": {
                      "State": "Generated"
                    }
                  },
                  {
                    "comissao (%)": {
                      "State": "Generated"
                    }
                  }
                ],
                "Units": [
                  "percentage",
                  "%"
                ]
              },
              "d_vendedore.loja": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dVendedores",
                    "ConceptualProperty": "Loja"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "loja": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_vendedore.nome_vendedor": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dVendedores",
                    "ConceptualProperty": "Nome_Vendedor"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "nome vendedor": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Nome_Vendedor": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "f_venda": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "fVendas"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "f venda": {
                      "State": "Generated"
                    }
                  },
                  {
                    "fVendas": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "venda": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  }
                ]
              },
              "f_venda.ID_cliente": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "fVendas",
                    "ConceptualProperty": "ID_Cliente"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ID cliente": {
                      "State": "Generated"
                    }
                  },
                  {
                    "ID_Cliente": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "identification cliente": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identity cliente": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identifier cliente": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "credential cliente": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "f_venda.ID_produto": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "fVendas",
                    "ConceptualProperty": "ID_Produto"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ID produto": {
                      "State": "Generated"
                    }
                  },
                  {
                    "ID_Produto": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "identification produto": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identity produto": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identifier produto": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "credential produto": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "f_venda.ID_venda": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "fVendas",
                    "ConceptualProperty": "ID_Venda"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ID venda": {
                      "State": "Generated"
                    }
                  },
                  {
                    "ID_Venda": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "venda": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "identification venda": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identity venda": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identifier venda": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "credential venda": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "f_venda.ID_vendedor": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "fVendas",
                    "ConceptualProperty": "ID_Vendedor"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ID vendedor": {
                      "State": "Generated"
                    }
                  },
                  {
                    "ID_Vendedor": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "identification vendedor": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identity vendedor": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identifier vendedor": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "credential vendedor": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "f_venda.data": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "fVendas",
                    "ConceptualProperty": "Data"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "data": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date": {
                      "State": "Generated",
                      "Weight": 0.7
                    }
                  },
                  {
                    "information": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "fact": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "info": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "statistic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "document": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "figure": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "record": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "f_venda.preco_unitario": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "fVendas",
                    "ConceptualProperty": "Preco_Unitario"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "preco unitario": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Preco_Unitario": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "f_venda.quantidade": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "fVendas",
                    "ConceptualProperty": "Quantidade"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "quantidade": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "f_venda.total_venda": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "fVendas",
                    "ConceptualProperty": "Total_Venda"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "total venda": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Total_Venda": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "venda": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "aggregate venda": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "overall venda": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "v_medidas_medida": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_medidas"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "_medida": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "v_medidas_medida.comissão_vendedor": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_medidas",
                    "ConceptualProperty": "Comissão Vendedor"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "comissão vendedor": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "v_medidas_medida.crescimento_percentual_de_vendas_ano_a_ano": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_medidas",
                    "ConceptualProperty": "Crescimento Percentual de Vendas (Ano a Ano)"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "crescimento percentual de vendas (ano a ano)": {
                      "State": "Generated"
                    }
                  },
                  {
                    "crescimento percentual de vendas": {
                      "State": "Generated",
                      "Weight": 0.75
                    }
                  }
                ]
              },
              "v_medidas_medida.de_contribuição_de_produto": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_medidas",
                    "ConceptualProperty": "% de Contribuição de Produto"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "% de contribuição de produto": {
                      "State": "Generated"
                    }
                  },
                  {
                    "percentage de contribuição de produto": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.624
                    }
                  },
                  {
                    "pct de contribuição de produto": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.605
                    }
                  }
                ]
              },
              "v_medidas_medida.frequência": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_medidas",
                    "ConceptualProperty": "Frequência"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "frequência": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "v_medidas_medida.monetário": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_medidas",
                    "ConceptualProperty": "Monetário"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "monetário": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "v_medidas_medida.ranking_de_vendedores": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_medidas",
                    "ConceptualProperty": "Ranking de Vendedores"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ranking de vendedores": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "v_medidas_medida.receita_acumulada": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_medidas",
                    "ConceptualProperty": "Receita Acumulada"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "receita acumulada": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "v_medidas_medida.recência": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_medidas",
                    "ConceptualProperty": "Recência"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "recência": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "v_medidas_medida.ticket_médio": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_medidas",
                    "ConceptualProperty": "Ticket Médio"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ticket médio": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "v_medidas_medida.variação_de_vendas": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_medidas",
                    "ConceptualProperty": "Variação de Vendas"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "variação de vendas": {
                      "State": "Generated"
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Relationships": {
              "d_calendario_date_ano_has_d_calendario_date_trimestre": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.date.trimestre"
                      },
                      "Subject": {
                        "Role": "d_calendario.date.ano"
                      }
                    },
                    "ID": "anos_have_trimestres",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.date.ano"
                      },
                      "Subject": {
                        "Role": "d_calendario.date.trimestre"
                      }
                    },
                    "ID": "trimestres_have_anos",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "ID": "trimestres_are_in_anos",
                    "Preposition": {
                      "Object": {
                        "Role": "d_calendario.date.ano"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "d_calendario.date.trimestre"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario.date.ano": {
                    "Target": {
                      "Entity": "d_calendario.date.ano"
                    }
                  },
                  "d_calendario.date.trimestre": {
                    "Target": {
                      "Entity": "d_calendario.date.trimestre"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_date_has_hierarquia_de_data": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.date.hierarquia_de_data"
                      },
                      "Subject": {
                        "Role": "d_calendario.date"
                      }
                    },
                    "ID": "dates_have_hierarquia_de_data",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario.date": {
                    "Target": {
                      "Entity": "d_calendario.date"
                    }
                  },
                  "d_calendario.date.hierarquia_de_data": {
                    "Target": {
                      "Entity": "d_calendario.date.hierarquia_de_data"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_date_hierarquia_de_data_has_d_calendario_date_ano": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.date.ano"
                      },
                      "Subject": {
                        "Role": "d_calendario.date.hierarquia_de_data"
                      }
                    },
                    "ID": "hierarquia_de_data_have_anos",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario.date.ano": {
                    "Target": {
                      "Entity": "d_calendario.date.ano"
                    }
                  },
                  "d_calendario.date.hierarquia_de_data": {
                    "Target": {
                      "Entity": "d_calendario.date.hierarquia_de_data"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_date_hierarquia_de_data_has_d_calendario_date_dia": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.date.dia"
                      },
                      "Subject": {
                        "Role": "d_calendario.date.hierarquia_de_data"
                      }
                    },
                    "ID": "hierarquia_de_data_have_dias",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario.date.dia": {
                    "Target": {
                      "Entity": "d_calendario.date.dia"
                    }
                  },
                  "d_calendario.date.hierarquia_de_data": {
                    "Target": {
                      "Entity": "d_calendario.date.hierarquia_de_data"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_date_hierarquia_de_data_has_d_calendario_date_mê": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.date.mê"
                      },
                      "Subject": {
                        "Role": "d_calendario.date.hierarquia_de_data"
                      }
                    },
                    "ID": "hierarquia_de_data_have_mê",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario.date.hierarquia_de_data": {
                    "Target": {
                      "Entity": "d_calendario.date.hierarquia_de_data"
                    }
                  },
                  "d_calendario.date.mê": {
                    "Target": {
                      "Entity": "d_calendario.date.mê"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_date_hierarquia_de_data_has_d_calendario_date_trimestre": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.date.trimestre"
                      },
                      "Subject": {
                        "Role": "d_calendario.date.hierarquia_de_data"
                      }
                    },
                    "ID": "hierarquia_de_data_have_trimestres",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario.date.hierarquia_de_data": {
                    "Target": {
                      "Entity": "d_calendario.date.hierarquia_de_data"
                    }
                  },
                  "d_calendario.date.trimestre": {
                    "Target": {
                      "Entity": "d_calendario.date.trimestre"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_date_mê_has_d_calendario_date_dia": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.date.dia"
                      },
                      "Subject": {
                        "Role": "d_calendario.date.mê"
                      }
                    },
                    "ID": "mê_have_dias",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.date.mê"
                      },
                      "Subject": {
                        "Role": "d_calendario.date.dia"
                      }
                    },
                    "ID": "dias_have_mê",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "ID": "dias_are_in_mê",
                    "Preposition": {
                      "Object": {
                        "Role": "d_calendario.date.mê"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "d_calendario.date.dia"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario.date.dia": {
                    "Target": {
                      "Entity": "d_calendario.date.dia"
                    }
                  },
                  "d_calendario.date.mê": {
                    "Target": {
                      "Entity": "d_calendario.date.mê"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_date_trimestre_has_d_calendario_date_mê": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.date.mê"
                      },
                      "Subject": {
                        "Role": "d_calendario.date.trimestre"
                      }
                    },
                    "ID": "trimestres_have_mê",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.date.trimestre"
                      },
                      "Subject": {
                        "Role": "d_calendario.date.mê"
                      }
                    },
                    "ID": "mê_have_trimestres",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "ID": "mê_are_in_trimestres",
                    "Preposition": {
                      "Object": {
                        "Role": "d_calendario.date.trimestre"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "d_calendario.date.mê"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario.date.mê": {
                    "Target": {
                      "Entity": "d_calendario.date.mê"
                    }
                  },
                  "d_calendario.date.trimestre": {
                    "Target": {
                      "Entity": "d_calendario.date.trimestre"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_has_ano": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.ano"
                      },
                      "Subject": {
                        "Role": "d_calendario"
                      }
                    },
                    "ID": "d_calendarios_have_anos",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario": {
                    "Target": {
                      "Entity": "d_calendario"
                    }
                  },
                  "d_calendario.ano": {
                    "Target": {
                      "Entity": "d_calendario.ano"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_has_ano_mê": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.ano_mê"
                      },
                      "Subject": {
                        "Role": "d_calendario"
                      }
                    },
                    "ID": "d_calendarios_have_ano_mê",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario": {
                    "Target": {
                      "Entity": "d_calendario"
                    }
                  },
                  "d_calendario.ano_mê": {
                    "Target": {
                      "Entity": "d_calendario.ano_mê"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_has_ano_mês_número": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.ano_mês_número"
                      },
                      "Subject": {
                        "Role": "d_calendario"
                      }
                    },
                    "ID": "d_calendarios_have_ano_mês_números",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario": {
                    "Target": {
                      "Entity": "d_calendario"
                    }
                  },
                  "d_calendario.ano_mês_número": {
                    "Target": {
                      "Entity": "d_calendario.ano_mês_número"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_has_date": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.date"
                      },
                      "Subject": {
                        "Role": "d_calendario"
                      }
                    },
                    "ID": "d_calendarios_have_dates",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario": {
                    "Target": {
                      "Entity": "d_calendario"
                    }
                  },
                  "d_calendario.date": {
                    "Target": {
                      "Entity": "d_calendario.date"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_has_dia_da_semana": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.dia_da_semana"
                      },
                      "Subject": {
                        "Role": "d_calendario"
                      }
                    },
                    "ID": "d_calendarios_have_dia_da_semanas",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario": {
                    "Target": {
                      "Entity": "d_calendario"
                    }
                  },
                  "d_calendario.dia_da_semana": {
                    "Target": {
                      "Entity": "d_calendario.dia_da_semana"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_has_mê": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.mê"
                      },
                      "Subject": {
                        "Role": "d_calendario"
                      }
                    },
                    "ID": "d_calendarios_have_mê",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario": {
                    "Target": {
                      "Entity": "d_calendario"
                    }
                  },
                  "d_calendario.mê": {
                    "Target": {
                      "Entity": "d_calendario.mê"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_has_mês_ano": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.mês_ano"
                      },
                      "Subject": {
                        "Role": "d_calendario"
                      }
                    },
                    "ID": "d_calendarios_have_mês_anos",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario": {
                    "Target": {
                      "Entity": "d_calendario"
                    }
                  },
                  "d_calendario.mês_ano": {
                    "Target": {
                      "Entity": "d_calendario.mês_ano"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_has_número_do_dia_da_semana": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.número_do_dia_da_semana"
                      },
                      "Subject": {
                        "Role": "d_calendario"
                      }
                    },
                    "ID": "d_calendarios_have_número_do_dia_da_semanas",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario": {
                    "Target": {
                      "Entity": "d_calendario"
                    }
                  },
                  "d_calendario.número_do_dia_da_semana": {
                    "Target": {
                      "Entity": "d_calendario.número_do_dia_da_semana"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_has_número_do_mê": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.número_do_mê"
                      },
                      "Subject": {
                        "Role": "d_calendario"
                      }
                    },
                    "ID": "d_calendarios_have_número_do_mê",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario": {
                    "Target": {
                      "Entity": "d_calendario"
                    }
                  },
                  "d_calendario.número_do_mê": {
                    "Target": {
                      "Entity": "d_calendario.número_do_mê"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_has_trimestre": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.trimestre"
                      },
                      "Subject": {
                        "Role": "d_calendario"
                      }
                    },
                    "ID": "d_calendarios_have_trimestres",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario": {
                    "Target": {
                      "Entity": "d_calendario"
                    }
                  },
                  "d_calendario.trimestre": {
                    "Target": {
                      "Entity": "d_calendario.trimestre"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_cliente_has_ID_cliente": {
                "Binding": {
                  "ConceptualEntity": "dClientes"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_cliente.ID_cliente"
                      },
                      "Subject": {
                        "Role": "d_cliente"
                      }
                    },
                    "ID": "d_clientes_have_ID_clientes",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_cliente": {
                    "Target": {
                      "Entity": "d_cliente"
                    }
                  },
                  "d_cliente.ID_cliente": {
                    "Target": {
                      "Entity": "d_cliente.ID_cliente"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_cliente_has_cidade": {
                "Binding": {
                  "ConceptualEntity": "dClientes"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_cliente.cidade"
                      },
                      "Subject": {
                        "Role": "d_cliente"
                      }
                    },
                    "ID": "d_clientes_have_cidades",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_cliente": {
                    "Target": {
                      "Entity": "d_cliente"
                    }
                  },
                  "d_cliente.cidade": {
                    "Target": {
                      "Entity": "d_cliente.cidade"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_cliente_has_estado": {
                "Binding": {
                  "ConceptualEntity": "dClientes"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_cliente.estado"
                      },
                      "Subject": {
                        "Role": "d_cliente"
                      }
                    },
                    "ID": "d_clientes_have_estado",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_cliente": {
                    "Target": {
                      "Entity": "d_cliente"
                    }
                  },
                  "d_cliente.estado": {
                    "Target": {
                      "Entity": "d_cliente.estado"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_cliente_has_idade": {
                "Binding": {
                  "ConceptualEntity": "dClientes"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_cliente.idade"
                      },
                      "Subject": {
                        "Role": "d_cliente"
                      }
                    },
                    "ID": "d_clientes_have_idades",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_cliente": {
                    "Target": {
                      "Entity": "d_cliente"
                    }
                  },
                  "d_cliente.idade": {
                    "Target": {
                      "Entity": "d_cliente.idade"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_cliente_has_nome_cliente": {
                "Binding": {
                  "ConceptualEntity": "dClientes"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_cliente.nome_cliente"
                      },
                      "Subject": {
                        "Role": "d_cliente"
                      }
                    },
                    "ID": "d_clientes_have_nome_clientes",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_cliente": {
                    "Target": {
                      "Entity": "d_cliente"
                    }
                  },
                  "d_cliente.nome_cliente": {
                    "Target": {
                      "Entity": "d_cliente.nome_cliente"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_produto_has_ID_produto": {
                "Binding": {
                  "ConceptualEntity": "dProdutos"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_produto.ID_produto"
                      },
                      "Subject": {
                        "Role": "d_produto"
                      }
                    },
                    "ID": "d_produtos_have_ID_produtos",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_produto": {
                    "Target": {
                      "Entity": "d_produto"
                    }
                  },
                  "d_produto.ID_produto": {
                    "Target": {
                      "Entity": "d_produto.ID_produto"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_produto_has_categoria": {
                "Binding": {
                  "ConceptualEntity": "dProdutos"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_produto.categoria"
                      },
                      "Subject": {
                        "Role": "d_produto"
                      }
                    },
                    "ID": "d_produtos_have_categorias",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_produto": {
                    "Target": {
                      "Entity": "d_produto"
                    }
                  },
                  "d_produto.categoria": {
                    "Target": {
                      "Entity": "d_produto.categoria"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_produto_has_nome_produto": {
                "Binding": {
                  "ConceptualEntity": "dProdutos"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_produto.nome_produto"
                      },
                      "Subject": {
                        "Role": "d_produto"
                      }
                    },
                    "ID": "d_produtos_have_nome_produtos",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_produto": {
                    "Target": {
                      "Entity": "d_produto"
                    }
                  },
                  "d_produto.nome_produto": {
                    "Target": {
                      "Entity": "d_produto.nome_produto"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_produto_has_preco_unitario": {
                "Binding": {
                  "ConceptualEntity": "dProdutos"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_produto.preco_unitario"
                      },
                      "Subject": {
                        "Role": "d_produto"
                      }
                    },
                    "ID": "d_produtos_have_preco_unitarios",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_produto": {
                    "Target": {
                      "Entity": "d_produto"
                    }
                  },
                  "d_produto.preco_unitario": {
                    "Target": {
                      "Entity": "d_produto.preco_unitario"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_vendedore_has_ID_vendedor": {
                "Binding": {
                  "ConceptualEntity": "dVendedores"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_vendedore.ID_vendedor"
                      },
                      "Subject": {
                        "Role": "d_vendedore"
                      }
                    },
                    "ID": "d_vendedores_have_ID_vendedors",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_vendedore": {
                    "Target": {
                      "Entity": "d_vendedore"
                    }
                  },
                  "d_vendedore.ID_vendedor": {
                    "Target": {
                      "Entity": "d_vendedore.ID_vendedor"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_vendedore_has_comissao": {
                "Binding": {
                  "ConceptualEntity": "dVendedores"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_vendedore.comissao"
                      },
                      "Subject": {
                        "Role": "d_vendedore"
                      }
                    },
                    "ID": "d_vendedores_have_comissaos",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_vendedore": {
                    "Target": {
                      "Entity": "d_vendedore"
                    }
                  },
                  "d_vendedore.comissao": {
                    "Target": {
                      "Entity": "d_vendedore.comissao"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_vendedore_has_loja": {
                "Binding": {
                  "ConceptualEntity": "dVendedores"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_vendedore.loja"
                      },
                      "Subject": {
                        "Role": "d_vendedore"
                      }
                    },
                    "ID": "d_vendedores_have_loja",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_vendedore": {
                    "Target": {
                      "Entity": "d_vendedore"
                    }
                  },
                  "d_vendedore.loja": {
                    "Target": {
                      "Entity": "d_vendedore.loja"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_vendedore_has_nome_vendedor": {
                "Binding": {
                  "ConceptualEntity": "dVendedores"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_vendedore.nome_vendedor"
                      },
                      "Subject": {
                        "Role": "d_vendedore"
                      }
                    },
                    "ID": "d_vendedores_have_nome_vendedors",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_vendedore": {
                    "Target": {
                      "Entity": "d_vendedore"
                    }
                  },
                  "d_vendedore.nome_vendedor": {
                    "Target": {
                      "Entity": "d_vendedore.nome_vendedor"
                    }
                  }
                },
                "State": "Generated"
              },
              "f_venda_has_ID_venda": {
                "Binding": {
                  "ConceptualEntity": "fVendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "f_venda.ID_venda"
                      },
                      "Subject": {
                        "Role": "f_venda"
                      }
                    },
                    "ID": "f_venda_have_ID_venda",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "f_venda": {
                    "Target": {
                      "Entity": "f_venda"
                    }
                  },
                  "f_venda.ID_venda": {
                    "Target": {
                      "Entity": "f_venda.ID_venda"
                    }
                  }
                },
                "State": "Generated"
              },
              "f_venda_has_d_calendario": {
                "Binding": {
                  "ConceptualEntity": "fVendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario"
                      },
                      "Subject": {
                        "Role": "f_venda"
                      }
                    },
                    "ID": "f_venda_have_d_calendarios",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "f_venda"
                      },
                      "Subject": {
                        "Role": "d_calendario"
                      }
                    },
                    "ID": "d_calendarios_have_f_venda",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario": {
                    "Nouns": [
                      {
                        "data": {
                          "State": "Generated"
                        }
                      }
                    ],
                    "Target": {
                      "Entity": "d_calendario"
                    }
                  },
                  "f_venda": {
                    "Target": {
                      "Entity": "f_venda"
                    }
                  }
                },
                "State": "Generated"
              },
              "f_venda_has_d_cliente": {
                "Binding": {
                  "ConceptualEntity": "fVendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_cliente"
                      },
                      "Subject": {
                        "Role": "f_venda"
                      }
                    },
                    "ID": "f_venda_have_d_clientes",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "f_venda"
                      },
                      "Subject": {
                        "Role": "d_cliente"
                      }
                    },
                    "ID": "d_clientes_have_f_venda",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_cliente": {
                    "Target": {
                      "Entity": "d_cliente"
                    }
                  },
                  "f_venda": {
                    "Target": {
                      "Entity": "f_venda"
                    }
                  }
                },
                "State": "Generated"
              },
              "f_venda_has_d_produto": {
                "Binding": {
                  "ConceptualEntity": "fVendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_produto"
                      },
                      "Subject": {
                        "Role": "f_venda"
                      }
                    },
                    "ID": "f_venda_have_d_produtos",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "f_venda"
                      },
                      "Subject": {
                        "Role": "d_produto"
                      }
                    },
                    "ID": "d_produtos_have_f_venda",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_produto": {
                    "Target": {
                      "Entity": "d_produto"
                    }
                  },
                  "f_venda": {
                    "Target": {
                      "Entity": "f_venda"
                    }
                  }
                },
                "State": "Generated"
              },
              "f_venda_has_d_vendedore": {
                "Binding": {
                  "ConceptualEntity": "fVendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_vendedore"
                      },
                      "Subject": {
                        "Role": "f_venda"
                      }
                    },
                    "ID": "f_venda_have_d_vendedores",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "f_venda"
                      },
                      "Subject": {
                        "Role": "d_vendedore"
                      }
                    },
                    "ID": "d_vendedores_have_f_venda",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_vendedore": {
                    "Target": {
                      "Entity": "d_vendedore"
                    }
                  },
                  "f_venda": {
                    "Target": {
                      "Entity": "f_venda"
                    }
                  }
                },
                "State": "Generated"
              },
              "f_venda_has_data": {
                "Binding": {
                  "ConceptualEntity": "fVendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "f_venda.data"
                      },
                      "Subject": {
                        "Role": "f_venda"
                      }
                    },
                    "ID": "f_venda_have_data",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "f_venda": {
                    "Target": {
                      "Entity": "f_venda"
                    }
                  },
                  "f_venda.data": {
                    "Target": {
                      "Entity": "f_venda.data"
                    }
                  }
                },
                "State": "Generated"
              },
              "f_venda_has_preco_unitario": {
                "Binding": {
                  "ConceptualEntity": "fVendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "f_venda.preco_unitario"
                      },
                      "Subject": {
                        "Role": "f_venda"
                      }
                    },
                    "ID": "f_venda_have_preco_unitarios",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "f_venda": {
                    "Target": {
                      "Entity": "f_venda"
                    }
                  },
                  "f_venda.preco_unitario": {
                    "Target": {
                      "Entity": "f_venda.preco_unitario"
                    }
                  }
                },
                "State": "Generated"
              },
              "f_venda_has_quantidade": {
                "Binding": {
                  "ConceptualEntity": "fVendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "f_venda.quantidade"
                      },
                      "Subject": {
                        "Role": "f_venda"
                      }
                    },
                    "ID": "f_venda_have_quantidades",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "f_venda": {
                    "Target": {
                      "Entity": "f_venda"
                    }
                  },
                  "f_venda.quantidade": {
                    "Target": {
                      "Entity": "f_venda.quantidade"
                    }
                  }
                },
                "State": "Generated"
              },
              "f_venda_has_total_venda": {
                "Binding": {
                  "ConceptualEntity": "fVendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "f_venda.total_venda"
                      },
                      "Subject": {
                        "Role": "f_venda"
                      }
                    },
                    "ID": "f_venda_have_total_venda",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "f_venda": {
                    "Target": {
                      "Entity": "f_venda"
                    }
                  },
                  "f_venda.total_venda": {
                    "Target": {
                      "Entity": "f_venda.total_venda"
                    }
                  }
                },
                "State": "Generated"
              },
              "f_venda_has_v_medidas_medida_crescimento_percentual_de_vendas_ano_a_ano": {
                "Binding": {
                  "ConceptualEntity": "fVendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_medidas_medida.crescimento_percentual_de_vendas_ano_a_ano"
                      },
                      "Subject": {
                        "Role": "f_venda"
                      }
                    },
                    "ID": "f_venda_have_crescimento_percentual_de_vendas_ano_a_ano",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "f_venda": {
                    "Target": {
                      "Entity": "f_venda"
                    }
                  },
                  "v_medidas_medida.crescimento_percentual_de_vendas_ano_a_ano": {
                    "Target": {
                      "Entity": "v_medidas_medida.crescimento_percentual_de_vendas_ano_a_ano"
                    }
                  }
                },
                "State": "Generated"
              },
              "f_venda_has_v_medidas_medida_de_contribuição_de_produto": {
                "Binding": {
                  "ConceptualEntity": "fVendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_medidas_medida.de_contribuição_de_produto"
                      },
                      "Subject": {
                        "Role": "f_venda"
                      }
                    },
                    "ID": "f_venda_have__de_contribuição_de_produto",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "f_venda": {
                    "Target": {
                      "Entity": "f_venda"
                    }
                  },
                  "v_medidas_medida.de_contribuição_de_produto": {
                    "Target": {
                      "Entity": "v_medidas_medida.de_contribuição_de_produto"
                    }
                  }
                },
                "State": "Generated"
              },
              "f_venda_has_v_medidas_medida_frequência": {
                "Binding": {
                  "ConceptualEntity": "fVendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_medidas_medida.frequência"
                      },
                      "Subject": {
                        "Role": "f_venda"
                      }
                    },
                    "ID": "f_venda_have_frequência",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "f_venda": {
                    "Target": {
                      "Entity": "f_venda"
                    }
                  },
                  "v_medidas_medida.frequência": {
                    "Target": {
                      "Entity": "v_medidas_medida.frequência"
                    }
                  }
                },
                "State": "Generated"
              },
              "f_venda_has_v_medidas_medida_monetário": {
                "Binding": {
                  "ConceptualEntity": "fVendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_medidas_medida.monetário"
                      },
                      "Subject": {
                        "Role": "f_venda"
                      }
                    },
                    "ID": "f_venda_have_monetário",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "f_venda": {
                    "Target": {
                      "Entity": "f_venda"
                    }
                  },
                  "v_medidas_medida.monetário": {
                    "Target": {
                      "Entity": "v_medidas_medida.monetário"
                    }
                  }
                },
                "State": "Generated"
              },
              "f_venda_has_v_medidas_medida_ticket_médio": {
                "Binding": {
                  "ConceptualEntity": "fVendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_medidas_medida.ticket_médio"
                      },
                      "Subject": {
                        "Role": "f_venda"
                      }
                    },
                    "ID": "f_venda_have_ticket_médio",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "f_venda": {
                    "Target": {
                      "Entity": "f_venda"
                    }
                  },
                  "v_medidas_medida.ticket_médio": {
                    "Target": {
                      "Entity": "v_medidas_medida.ticket_médio"
                    }
                  }
                },
                "State": "Generated"
              },
              "f_venda_has_v_medidas_medida_variação_de_vendas": {
                "Binding": {
                  "ConceptualEntity": "fVendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_medidas_medida.variação_de_vendas"
                      },
                      "Subject": {
                        "Role": "f_venda"
                      }
                    },
                    "ID": "f_venda_have_variação_de_vendas",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "f_venda": {
                    "Target": {
                      "Entity": "f_venda"
                    }
                  },
                  "v_medidas_medida.variação_de_vendas": {
                    "Target": {
                      "Entity": "v_medidas_medida.variação_de_vendas"
                    }
                  }
                },
                "State": "Generated"
              },
              "v_medidas_medida_has_comissão_vendedor": {
                "Binding": {
                  "ConceptualEntity": "_medidas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_medidas_medida.comissão_vendedor"
                      },
                      "Subject": {
                        "Role": "v_medidas_medida"
                      }
                    },
                    "ID": "Phrasing_medidas_have_comissão_vendedor",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "v_medidas_medida": {
                    "Target": {
                      "Entity": "v_medidas_medida"
                    }
                  },
                  "v_medidas_medida.comissão_vendedor": {
                    "Target": {
                      "Entity": "v_medidas_medida.comissão_vendedor"
                    }
                  }
                },
                "State": "Generated"
              },
              "v_medidas_medida_has_ranking_de_vendedores": {
                "Binding": {
                  "ConceptualEntity": "_medidas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_medidas_medida.ranking_de_vendedores"
                      },
                      "Subject": {
                        "Role": "v_medidas_medida"
                      }
                    },
                    "ID": "Phrasing_medidas_have_ranking_de_vendedores",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "v_medidas_medida": {
                    "Target": {
                      "Entity": "v_medidas_medida"
                    }
                  },
                  "v_medidas_medida.ranking_de_vendedores": {
                    "Target": {
                      "Entity": "v_medidas_medida.ranking_de_vendedores"
                    }
                  }
                },
                "State": "Generated"
              },
              "v_medidas_medida_has_receita_acumulada": {
                "Binding": {
                  "ConceptualEntity": "_medidas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_medidas_medida.receita_acumulada"
                      },
                      "Subject": {
                        "Role": "v_medidas_medida"
                      }
                    },
                    "ID": "Phrasing_medidas_have_receita_acumulada",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "v_medidas_medida": {
                    "Target": {
                      "Entity": "v_medidas_medida"
                    }
                  },
                  "v_medidas_medida.receita_acumulada": {
                    "Target": {
                      "Entity": "v_medidas_medida.receita_acumulada"
                    }
                  }
                },
                "State": "Generated"
              },
              "v_medidas_medida_has_recência": {
                "Binding": {
                  "ConceptualEntity": "_medidas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_medidas_medida.recência"
                      },
                      "Subject": {
                        "Role": "v_medidas_medida"
                      }
                    },
                    "ID": "Phrasing_medidas_have_recência",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "v_medidas_medida": {
                    "Target": {
                      "Entity": "v_medidas_medida"
                    }
                  },
                  "v_medidas_medida.recência": {
                    "Target": {
                      "Entity": "v_medidas_medida.recência"
                    }
                  }
                },
                "State": "Generated"
              }
            },
            "Version": "3.5.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "AutoDetected_0df724ba-0936-42c2-b403-a10e20f43de3",
        "fromColumn": "ID_Cliente",
        "fromTable": "fVendas",
        "toColumn": "ID_Cliente",
        "toTable": "dClientes"
      },
      {
        "name": "AutoDetected_a8979676-a1bb-4c92-b2ac-ca8860ef3cf7",
        "fromColumn": "ID_Produto",
        "fromTable": "fVendas",
        "toColumn": "ID_Produto",
        "toTable": "dProdutos"
      },
      {
        "name": "AutoDetected_9ec25f67-06c9-4050-b07d-f14e3ded2d2a",
        "fromColumn": "ID_Vendedor",
        "fromTable": "fVendas",
        "toColumn": "ID_Vendedor",
        "toTable": "dVendedores"
      },
      {
        "name": "a71ef48a-4320-4699-be04-8308d606ef64",
        "fromColumn": "Data",
        "fromTable": "dCalendario_Power Query",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_69be3095-3921-4e2b-b0ef-7c99a90d4cb0"
      },
      {
        "name": "07def5db-12dd-492f-bdcf-cfba50031576",
        "fromColumn": "Date",
        "fromTable": "dCalendario",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_84896ef3-679a-443a-a9b8-3f8521e1a0dc"
      },
      {
        "name": "59551982-aaf0-b121-5fa2-737de797d41e",
        "fromColumn": "Data",
        "fromTable": "fVendas",
        "toColumn": "Date",
        "toTable": "dCalendario"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "dClientes",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_Cliente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5f3fed49-8fe1-4a41-b013-75c4a56f0d8f",
            "sourceColumn": "ID_Cliente",
            "summarizeBy": "none"
          },
          {
            "name": "Nome_Cliente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1d10517d-1e4a-4e73-b995-005585f972ac",
            "sourceColumn": "Nome_Cliente",
            "summarizeBy": "none"
          },
          {
            "name": "Cidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9dae98f7-4505-4786-989b-04d56dfb34ae",
            "sourceColumn": "Cidade",
            "summarizeBy": "none"
          },
          {
            "name": "Estado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3bee0769-f70e-4a5a-ae92-f5ce2fc54023",
            "sourceColumn": "Estado",
            "summarizeBy": "none"
          },
          {
            "name": "Idade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "237ff1ee-ab01-4e92-9f68-4d5d7f6d4ab8",
            "sourceColumn": "Idade",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b53a6367-51e1-4569-8cf8-d4af867f4df9",
        "partitions": [
          {
            "name": "dClientes",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\TM416YS\\OneDrive - EY\\Documents\\Repos_Git\\Analytics\\Cases\\Power BI\\case 01\\data\\Dataset_Vendas.xlsx\"), null, true),",
                "    Clientes_Sheet = Source{[Item=\"Clientes\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Clientes_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ID_Cliente\", Int64.Type}, {\"Nome_Cliente\", type text}, {\"Cidade\", type text}, {\"Estado\", type text}, {\"Idade\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dProdutos",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_Produto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a1be948d-6cbd-4744-83b2-03470c46ec99",
            "sourceColumn": "ID_Produto",
            "summarizeBy": "none"
          },
          {
            "name": "Nome_Produto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "76bfb47c-2675-4755-b47c-43e160183481",
            "sourceColumn": "Nome_Produto",
            "summarizeBy": "none"
          },
          {
            "name": "Categoria",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "923ede8a-5fac-4a27-8458-d172c1a48298",
            "sourceColumn": "Categoria",
            "summarizeBy": "none"
          },
          {
            "name": "Preco_Unitario",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b61b32ce-cc67-4f21-b922-40982ea7886a",
            "sourceColumn": "Preco_Unitario",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6cafd5e9-def4-4089-aa7b-dfb16f06de1e",
        "partitions": [
          {
            "name": "dProdutos",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\TM416YS\\OneDrive - EY\\Documents\\Repos_Git\\Analytics\\Cases\\Power BI\\case 01\\data\\Dataset_Vendas.xlsx\"), null, true),",
                "    Produtos_Sheet = Source{[Item=\"Produtos\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Produtos_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ID_Produto\", Int64.Type}, {\"Nome_Produto\", type text}, {\"Categoria\", type text}, {\"Preco_Unitario\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fVendas",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_Venda",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d42a7d1a-9202-4033-be27-e3ebf33cc46c",
            "sourceColumn": "ID_Venda",
            "summarizeBy": "sum"
          },
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "d84b1962-13e8-4ffc-81f0-f278fad204ab",
            "sourceColumn": "Data",
            "summarizeBy": "none"
          },
          {
            "name": "ID_Produto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3532a527-99b9-4aff-8c29-22f41fed3603",
            "sourceColumn": "ID_Produto",
            "summarizeBy": "none"
          },
          {
            "name": "ID_Cliente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eeee52ac-5b9d-4d78-9688-1fe42408c53f",
            "sourceColumn": "ID_Cliente",
            "summarizeBy": "none"
          },
          {
            "name": "ID_Vendedor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8c238ba3-ecc5-4b35-b839-fe64992d4027",
            "sourceColumn": "ID_Vendedor",
            "summarizeBy": "none"
          },
          {
            "name": "Quantidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "23025eda-bc60-41e9-afa1-3cdcdd2a3ba1",
            "sourceColumn": "Quantidade",
            "summarizeBy": "sum"
          },
          {
            "name": "Preco_Unitario",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "91fa749b-6358-4c21-a0c8-ac1c048b6996",
            "sourceColumn": "Preco_Unitario",
            "summarizeBy": "sum"
          },
          {
            "name": "Total_Venda",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "641f4868-8db5-41db-a011-ff06b8bb276d",
            "sourceColumn": "Total_Venda",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "07d15605-46cc-4d8d-abdc-cc08128abd9f",
        "partitions": [
          {
            "name": "fVendas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\TM416YS\\OneDrive - EY\\Documents\\Repos_Git\\Analytics\\Cases\\Power BI\\case 01\\data\\Dataset_Vendas.xlsx\"), null, true),",
                "    Vendas_Sheet = Source{[Item=\"Vendas\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Vendas_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ID_Venda\", Int64.Type}, {\"Data\", type datetime}, {\"ID_Produto\", Int64.Type}, {\"ID_Cliente\", Int64.Type}, {\"ID_Vendedor\", Int64.Type}, {\"Quantidade\", Int64.Type}, {\"Preco_Unitario\", Int64.Type}, {\"Total_Venda\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_a2a698c7-be05-4e55-8d0c-cb5b4e6eb308",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d6150adf-6df9-46f6-ad40-5328a8f8e86d",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "92d0319e-d186-48c3-b7ad-4f1caf59a5d2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7690271b-cfe3-4940-ada3-55e25acc5d44",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "691e2401-75e2-414c-b7b3-f3fa93f056f2",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3afaeea5-2db7-4ab9-9c44-320b05aafefc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "fcffdde1-150e-47c2-8b79-7eb8b97e21bb",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2000d2b0-2877-4605-ae8e-e2a30e85aa26",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "ecb522b9-1d4f-421b-8b55-adefa09fb79d",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "beb3b3df-2c2a-4daa-ab47-c2e7cdaef551",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "6d7e763f-9066-4bca-a4f3-fdb3b51826fc",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "bc6183d5-61e1-45b1-94bf-70f095130564",
                "ordinal": 3
              }
            ],
            "lineageTag": "e54eeab4-9d0e-414b-9f1b-2ff9570e5807"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "f430ce71-87ed-405e-b1b7-62358784abda",
        "partitions": [
          {
            "name": "DateTableTemplate_a2a698c7-be05-4e55-8d0c-cb5b4e6eb308",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dVendedores",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_Vendedor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cd8d39c0-5c9c-4777-bc62-f8e5b46bc059",
            "sourceColumn": "ID_Vendedor",
            "summarizeBy": "none"
          },
          {
            "name": "Nome_Vendedor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7f12b0df-0a33-4614-92d9-3a35d0e7099f",
            "sourceColumn": "Nome_Vendedor",
            "summarizeBy": "none"
          },
          {
            "name": "Loja",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a5ab628e-f9be-4fa6-85d8-d814ae39c910",
            "sourceColumn": "Loja",
            "summarizeBy": "none"
          },
          {
            "name": "Comissao (%)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "688c59d5-8332-463f-a338-c9508d96324d",
            "sourceColumn": "Comissao (%)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1a4b18ac-5e05-489b-afaa-59015f4ebae6",
        "partitions": [
          {
            "name": "dVendedores",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\TM416YS\\OneDrive - EY\\Documents\\Repos_Git\\Analytics\\Cases\\Power BI\\case 01\\data\\Dataset_Vendas.xlsx\"), null, true),",
                "    Vendedores_Sheet = Source{[Item=\"Vendedores\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Vendedores_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ID_Vendedor\", Int64.Type}, {\"Nome_Vendedor\", type text}, {\"Loja\", type text}, {\"Comissao (%)\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dCalendario",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "89853faf6edd47cea1fc48e8025d88bf"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "fc1f7089-5701-4a67-ab51-cfee032bdd90",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_84896ef3-679a-443a-a9b8-3f8521e1a0dc"
                },
                "isDefault": true,
                "relationship": "07def5db-12dd-492f-bdcf-cfba50031576"
              }
            ]
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "53559000-4ca1-4e46-91c7-b34e0c72cff7",
            "sourceColumn": "[Ano]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a906ef89-fe9a-4fb4-83e2-31f5e2ed25de",
            "sourceColumn": "[Mês]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Número do Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "95262c1b-b222-480f-a5a8-32dca4fd1402",
            "sourceColumn": "[Número do Mês]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f22027c3-7d8a-4d4f-a553-af0d70cc16bd",
            "sourceColumn": "[Trimestre]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dia da Semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "bcf52810-9f7a-4f9b-870a-80a346ff6e36",
            "sourceColumn": "[Dia da Semana]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Número do Dia da Semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "bf32dee1-cb3c-4279-bb6f-f58a9f8855ba",
            "sourceColumn": "[Número do Dia da Semana]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "AnoMês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "062174cd-7854-4358-b038-d11a4b0a531b",
            "sourceColumn": "[AnoMês]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "AnoMês_Número",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f437e9a7-9b92-4572-add9-4ba32c198107",
            "sourceColumn": "[AnoMês_Número]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "MêsAno",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "aefbe614-3906-4bb7-b84d-24fefd47df19",
            "sortByColumn": "AnoMês_Número",
            "sourceColumn": "[MêsAno]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "ba936737-1657-4716-aa34-69fc5aa48c37",
        "partitions": [
          {
            "name": "dCalendario",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "ADDCOLUMNS (",
                "    CALENDAR (MIN(fVendas[Data]), MAX(fVendas[Data])),",
                "    \"Ano\", YEAR([Date]),",
                "    \"Mês\", FORMAT([Date], \"MMMM\"),",
                "    \"AnoMês\", FORMAT([Date], \"yyyy.MMM\"),",
                "    \"AnoMês_Número\", FORMAT([Date], \"yyyyMM\"),",
                "    \"MêsAno\", FORMAT([Date], \"MMM.yyyy\"),",
                "    \"Número do Mês\", MONTH([Date]),",
                "    \"Trimestre\", \"Q\" & FORMAT([Date], \"Q\"),",
                "    \"Dia da Semana\", FORMAT([Date], \"dddd\"),",
                "    \"Número do Dia da Semana\", WEEKDAY([Date], 2)",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dCalendario_Power Query",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "e28d4369-7743-4388-90f0-731670103c5b",
            "sourceColumn": "Data",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_69be3095-3921-4e2b-b0ef-7c99a90d4cb0"
                },
                "isDefault": true,
                "relationship": "a71ef48a-4320-4699-be04-8308d606ef64"
              }
            ]
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "83ff9dce-feec-428f-af8b-3d7ff02b4d4f",
            "sourceColumn": "Ano",
            "summarizeBy": "sum"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "6e621e4a-372d-42d3-8498-32b19c56c0c1",
            "sourceColumn": "Mês",
            "summarizeBy": "none"
          },
          {
            "name": "Número do Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "e19bd334-2803-4082-9e35-9a0beee44853",
            "sourceColumn": "Número do Mês",
            "summarizeBy": "sum"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ff2c8e80-8b88-4d63-a597-aad3a9dc142f",
            "sourceColumn": "Trimestre",
            "summarizeBy": "none"
          },
          {
            "name": "Dia da Semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "7b9de7bf-6d5a-4661-aedb-558f7cafbdf3",
            "sourceColumn": "Dia da Semana",
            "summarizeBy": "none"
          },
          {
            "name": "Número do Dia da Semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "6b3f64a9-a119-4255-afac-91d20b0cd21d",
            "sourceColumn": "Número do Dia da Semana",
            "summarizeBy": "sum"
          }
        ],
        "isHidden": true,
        "lineageTag": "398bb8f3-c631-47da-8080-9f9c98069ef5",
        "partitions": [
          {
            "name": "dCalendario_Power Query",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    DataInicio = #date(2023, 1, 1),",
                "    DataFim = #date(2025, 12, 31),",
                "    NumeroDias = Duration.Days(DataFim - DataInicio) + 1,",
                "    ListaDatas = List.Dates(DataInicio, NumeroDias, #duration(1,0,0,0)),",
                "    TabelaCalendario = Table.FromList(ListaDatas, Splitter.SplitByNothing(), {\"Data\"}),",
                "    TipoCorreto = Table.TransformColumnTypes(TabelaCalendario,{{\"Data\", type date}}),",
                "    ColunasExtras = Table.AddColumn(TipoCorreto, \"Ano\", each Date.Year([Data]), type number),",
                "    ColunasExtras2 = Table.AddColumn(ColunasExtras, \"Mês\", each Date.MonthName([Data]), type text),",
                "    ColunasExtras3 = Table.AddColumn(ColunasExtras2, \"Número do Mês\", each Date.Month([Data]), type number),",
                "    ColunasExtras4 = Table.AddColumn(ColunasExtras3, \"Trimestre\", each \"Q\" & Number.ToText(Date.QuarterOfYear([Data])), type text),",
                "    ColunasExtras5 = Table.AddColumn(ColunasExtras4, \"Dia da Semana\", each Date.DayOfWeekName([Data]), type text),",
                "    ColunasExtras6 = Table.AddColumn(ColunasExtras5, \"Número do Dia da Semana\", each Date.DayOfWeek([Data], Day.Sunday) + 1, type number)",
                "in",
                "    ColunasExtras6"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_69be3095-3921-4e2b-b0ef-7c99a90d4cb0",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ddb792b6-ce31-4db4-86b9-30f3d8e89434",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6c07b3cb-c478-4576-b90b-dfd833c22ce3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "19eefd83-707e-491b-a246-00583cb557b2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "c4a2481e-33d8-4d64-af73-a40584ca4d2b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e7dc1778-a38f-4193-b0b9-66fe4831ce90",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "aa963de9-27ce-4830-86bf-d9f8678606fc",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b7ee7e78-1aab-45cf-b74b-6dae698b08a8",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "a55c9195-a38c-4ef1-b9bd-b9cd04b1cdfe",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "b94f73ae-81e2-4059-b706-7706d4df4337",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "efd3d321-12d5-4987-9814-998068a94ce3",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "7799bd9e-cd05-4e73-96ed-7c9dcbaf3957",
                "ordinal": 3
              }
            ],
            "lineageTag": "319dad35-feea-4517-9924-ca8cdc041c0b"
          }
        ],
        "isHidden": true,
        "lineageTag": "81462f90-d4ec-464a-b4d4-e5f64b25f41c",
        "partitions": [
          {
            "name": "LocalDateTable_69be3095-3921-4e2b-b0ef-7c99a90d4cb0",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dCalendario_Power Query'[Data])), 1, 1), Date(Year(MAX('dCalendario_Power Query'[Data])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_84896ef3-679a-443a-a9b8-3f8521e1a0dc",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "fa35a731-db42-40d7-bb67-93277615617d",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3cea99ee-e227-44ff-87d8-f2310e4672a4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "390ebd5d-fa9e-463e-9622-95ea6a2199ad",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "b0170d02-af0f-42d7-8353-e1fc4388c38d",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "62ad1ac9-4319-4f8e-9384-e8fbe14efe21",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "9e2e1c1e-4a54-43a5-89d9-d8ddb1e21750",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e17c6586-90db-4585-99eb-42e2c4c9743c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "e68d437f-38e9-467c-8ac7-0b27ef31e1c1",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "14db5af5-d19e-409e-aae1-85dde65910cb",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "f7a55ec3-f898-45c2-85f4-457752d1ac7d",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "48cf277d-9d3a-42bd-8c37-7734b934ef7b",
                "ordinal": 3
              }
            ],
            "lineageTag": "2ee06529-d145-42d4-90a2-c794da09b822"
          }
        ],
        "isHidden": true,
        "lineageTag": "6ee33e69-b739-4d5a-8474-4109afee5015",
        "partitions": [
          {
            "name": "LocalDateTable_84896ef3-679a-443a-a9b8-3f8521e1a0dc",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dCalendario'[Date])), 1, 1), Date(Year(MAX('dCalendario'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "_medidas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "lineageTag": "cd7d4d38-ece8-4fcf-ae04-e9ad81c76fd9",
        "measures": [
          {
            "name": "Ticket Médio",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Vendas",
            "expression": [
              "",
              "DIVIDE(SUM(fVendas[Total_Venda]), COUNT(fVendas[ID_Venda]), 0) + 0",
              "",
              "--Calcula o valor médio de uma venda."
            ],
            "lineageTag": "cf6eee79-2778-4c74-8f1e-7889ba72124f"
          },
          {
            "name": "Receita Acumulada",
            "displayFolder": "Vendas",
            "expression": [
              "",
              "TOTALYTD(SUM(fVendas[Total_Venda]), dCalendario[Date]) + 0",
              "",
              "--Mostra a soma cumulativa das vendas ao longo do ano."
            ],
            "formatString": "#,0",
            "lineageTag": "f82f3cec-6b56-4054-9e01-e73269e28569"
          },
          {
            "name": "Crescimento Percentual de Vendas (Ano a Ano)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Vendas",
            "expression": [
              "",
              "VAR AnoAnterior = ",
              "    CALCULATE(SUM(fVendas[Total_Venda]), SAMEPERIODLASTYEAR(dCalendario[Date]))",
              "RETURN ",
              "    DIVIDE(SUM(fVendas[Total_Venda]) - AnoAnterior, AnoAnterior, 0)",
              "",
              "--Mede a evolução da receita comparando com o mesmo período do ano anterior."
            ],
            "lineageTag": "897a64a5-dcc1-4395-b104-754eb9e64368"
          },
          {
            "name": "Ranking de Vendedores",
            "displayFolder": "Vendedor",
            "expression": [
              "",
              "RANKX(ALL(dVendedores), SUM(fVendas[Total_Venda]), , DESC, DENSE)",
              "",
              "--Cria um ranking dos vendedores com base no faturamento total."
            ],
            "formatString": "0",
            "lineageTag": "6352a7d1-2205-4247-ab92-ab4f72fcbd14"
          },
          {
            "name": "Recência",
            "displayFolder": "Clientes",
            "expression": [
              "",
              "VAR UltimaCompra = ",
              "    CALCULATE(MAX(fVendas[Data]), ALLEXCEPT(fVendas, fVendas[ID_Cliente]))",
              "RETURN ",
              "    DATEDIFF(UltimaCompra, TODAY(), DAY)",
              "",
              "--Recência (dias desde a última compra de cada cliente)"
            ],
            "formatString": "0",
            "lineageTag": "da140831-ee83-47c4-ab4c-54a13d42781f"
          },
          {
            "name": "Frequência",
            "displayFolder": "Clientes",
            "expression": [
              "",
              "CALCULATE(COUNT(fVendas[ID_Venda]), ALLEXCEPT(fVendas, fVendas[ID_Cliente]))",
              "",
              "--Frequência (quantidade de compras feitas pelo cliente)"
            ],
            "formatString": "0",
            "lineageTag": "8e09b78a-4a0c-4826-afa4-8bc5d13193bc"
          },
          {
            "name": "Monetário",
            "displayFolder": "Clientes",
            "expression": [
              "",
              "CALCULATE(SUM(fVendas[Total_Venda]), ALLEXCEPT(fVendas, fVendas[ID_Cliente]))",
              "",
              "--Valor Monetário (total gasto pelo cliente)"
            ],
            "formatString": "0",
            "lineageTag": "d8ca0d2c-9dc6-44cf-b811-e7d9846b2fb7"
          },
          {
            "name": "Variação de Vendas",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Vendas",
            "expression": [
              "",
              "VAR VendaAtual = SUM(fVendas[Total_Venda])",
              "VAR VendaPeriodoAnterior = ",
              "    CALCULATE(SUM(fVendas[Total_Venda]), DATEADD(dCalendario[Date], -1, MONTH))",
              "RETURN ",
              "    DIVIDE(VendaAtual - VendaPeriodoAnterior, VendaPeriodoAnterior, 0)",
              "",
              "--Compara o faturamento entre diferentes períodos de tempo."
            ],
            "lineageTag": "e3a96efe-69c9-4a03-b895-9169f4d924e1"
          },
          {
            "name": "% de Contribuição de Produto",
            "displayFolder": "Vendas",
            "expression": [
              "",
              "DIVIDE(SUM(fVendas[Total_Venda]), CALCULATE(SUM(fVendas[Total_Venda]), ALL(fVendas)), 0)",
              "",
              "--Mede a participação de cada produto no faturamento total."
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "fd308ae5-b829-4a58-a9ed-8ea63fac97b6"
          },
          {
            "name": "Comissão Vendedor",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Vendedor",
            "expression": [
              "",
              "SUMX(",
              "    fVendas,",
              "    IF(fVendas[Total_Venda] > 10000, fVendas[Total_Venda] * 0.05, 0)",
              ")",
              "",
              "--Aplica uma regra de comissão personalizada."
            ],
            "lineageTag": "a32e6c74-a214-4310-aafc-ce7ed6450ae8"
          }
        ],
        "partitions": [
          {
            "name": "_medidas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}