table f_animal
	lineageTag: 1d037600-e49d-4ca9-98d4-dc63a0e9245a

	column 'Kennel ID'
		dataType: int64
		formatString: 0
		lineageTag: f0d370e6-7fcf-468a-a286-d3fe215b32a3
		summarizeBy: count
		sourceColumn: Kennel ID

		annotation SummarizationSetBy = Automatic

	column 'Animal ID'
		dataType: string
		lineageTag: 89fa0bca-7864-46fc-a67c-2fbe82c93903
		summarizeBy: none
		sourceColumn: Animal ID

		annotation SummarizationSetBy = Automatic

	column 'Animal Name'
		dataType: string
		lineageTag: 6b2484f4-feb3-425d-8206-5a69c835c6a2
		summarizeBy: none
		sourceColumn: Animal Name

		annotation SummarizationSetBy = Automatic

	column 'Animal Type'
		dataType: string
		lineageTag: 1831ef6d-0228-446c-aeb9-d2538d4de92b
		summarizeBy: none
		sourceColumn: Animal Type

		annotation SummarizationSetBy = Automatic

	column 'Primary Color'
		dataType: string
		lineageTag: f3a43fbe-5c6f-4d3a-985f-19f74c157873
		summarizeBy: none
		sourceColumn: Primary Color

		annotation SummarizationSetBy = Automatic

	column 'Secondary Color'
		dataType: string
		lineageTag: 632bce8e-e210-43a8-8b84-16b3a18b6701
		summarizeBy: none
		sourceColumn: Secondary Color

		annotation SummarizationSetBy = Automatic

	column Sex
		dataType: string
		lineageTag: 093de1c4-3ba1-43bf-b3e7-617c2e6bb7e9
		summarizeBy: none
		sourceColumn: Sex

		annotation SummarizationSetBy = Automatic

	column DOB
		dataType: dateTime
		formatString: Long Date
		lineageTag: 12b20996-dfa3-4c02-b1c0-f426915bb3a7
		summarizeBy: none
		sourceColumn: DOB

		variation Variation
			isDefault
			relationship: 783927f6-4c93-41e2-8fbd-6b4a8e3dead2
			defaultHierarchy: LocalDateTable_b7992f31-7fec-4aa6-8b43-912ff4f51af7.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Intake Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 0fd53459-5194-443b-9b63-bdb3127e1e6f
		summarizeBy: none
		sourceColumn: Intake Date

		variation Variation
			isDefault
			relationship: e9bd0bba-014a-4163-b83e-80dcbbb60bd3
			defaultHierarchy: LocalDateTable_1c977722-4363-4a65-a3e8-7f9126d30379.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Intake Condition'
		dataType: string
		lineageTag: b15c8178-f0e1-4ee4-a761-6e381dfd7c2a
		summarizeBy: none
		sourceColumn: Intake Condition

		annotation SummarizationSetBy = Automatic

	column 'Intake Type'
		dataType: string
		lineageTag: 47e6f1ff-3986-454d-8cb5-f28af1a11e93
		summarizeBy: none
		sourceColumn: Intake Type

		annotation SummarizationSetBy = Automatic

	column 'Intake Subtype'
		dataType: string
		lineageTag: 83905b05-7e24-4842-9e04-623660bdf00f
		summarizeBy: none
		sourceColumn: Intake Subtype

		annotation SummarizationSetBy = Automatic

	column 'Reason for Intake'
		dataType: string
		lineageTag: 17007b15-118f-4fcc-bbb3-96b764200950
		summarizeBy: none
		sourceColumn: Reason for Intake

		annotation SummarizationSetBy = Automatic

	column 'Outcome Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: d23a9bd3-3949-4059-9fdc-42da9a798271
		summarizeBy: none
		sourceColumn: Outcome Date

		variation Variation
			isDefault
			relationship: ef21289b-fb08-4ef7-9898-33fee183ef5f
			defaultHierarchy: LocalDateTable_cb623485-deb3-4ff5-b233-a2e7e5a339ca.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Crossing
		dataType: string
		lineageTag: cd16ffd7-d1fc-4d26-8cd4-0f421efbda00
		summarizeBy: none
		sourceColumn: Crossing

		annotation SummarizationSetBy = Automatic

	column Jurisdiction
		dataType: string
		lineageTag: a9fe8f39-21d3-4224-90d8-e62d6900aa0e
		summarizeBy: none
		sourceColumn: Jurisdiction

		annotation SummarizationSetBy = Automatic

	column 'Outcome Type'
		dataType: string
		lineageTag: b2d064a5-9e3e-4fe8-8744-7748fafa91da
		summarizeBy: none
		sourceColumn: Outcome Type

		annotation SummarizationSetBy = Automatic

	column 'Outcome Subtype'
		dataType: string
		lineageTag: 3dea23bb-76ce-4a38-849d-2bfaf42b00cf
		summarizeBy: none
		sourceColumn: Outcome Subtype

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: c4ae5fab-5cd2-486e-8cfb-3d3135bcd3c3
		summarizeBy: sum
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column longitude
		dataType: double
		lineageTag: 2d0ac86b-d269-44d0-80fe-b0cdb499a78e
		summarizeBy: sum
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column intake_is_dead
		dataType: string
		lineageTag: b5d1eb19-c6c8-468a-9329-c0d891144bb1
		summarizeBy: none
		sourceColumn: intake_is_dead

		annotation SummarizationSetBy = Automatic

	column geopoint
		dataType: string
		lineageTag: 899c188d-66c4-4b32-aae1-f31d6bc4787f
		summarizeBy: none
		sourceColumn: geopoint

		annotation SummarizationSetBy = Automatic

	column intake_duration
		dataType: int64
		formatString: 0
		lineageTag: 40102aea-4fa4-4f16-acac-ff381db8b63f
		summarizeBy: sum
		sourceColumn: intake_duration

		annotation SummarizationSetBy = Automatic

	column is_current_month
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: aa2c625e-50b6-48e6-bd1f-52e0c27a0819
		summarizeBy: none
		sourceColumn: is_current_month

		annotation SummarizationSetBy = Automatic

	column outcome_is_dead
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: aae16630-5640-4d26-ae22-a9d7b97ab372
		summarizeBy: none
		sourceColumn: outcome_is_dead

		annotation SummarizationSetBy = Automatic

	column outcome_is_current
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b5f916ce-655c-4b2c-a415-8ed66be53c73
		summarizeBy: none
		sourceColumn: outcome_is_current

		annotation SummarizationSetBy = Automatic

	column outcome_is_other
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 31efd112-87ad-4de5-8086-a2a7759fd53e
		summarizeBy: none
		sourceColumn: outcome_is_other

		annotation SummarizationSetBy = Automatic

	column outcome_is_alive
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 55356481-81ae-4c53-ac81-6916b09706f8
		summarizeBy: none
		sourceColumn: outcome_is_alive

		annotation SummarizationSetBy = Automatic

	column was_outcome_alive
		dataType: int64
		formatString: 0
		lineageTag: e88a807c-0da3-4859-b9d9-982e385e58e5
		summarizeBy: sum
		sourceColumn: was_outcome_alive

		annotation SummarizationSetBy = Automatic

	partition f_animal = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\marco\OneDrive\Documentos\Repositorios\Git\Analytics\OnyxData\2025.12\data\DataDNA Dataset Challenge - Animal Shelter Operations - December 2025.csv"),[Delimiter=",", Columns=29, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Kennel ID", Int64.Type}, {"Animal ID", type text}, {"Animal Name", type text}, {"Animal Type", type text}, {"Primary Color", type text}, {"Secondary Color", type text}, {"Sex", type text}, {"DOB", type date}, {"Intake Date", type date}, {"Intake Condition", type text}, {"Intake Type", type text}, {"Intake Subtype", type text}, {"Reason for Intake", type text}, {"Outcome Date", type date}, {"Crossing", type text}, {"Jurisdiction", type text}, {"Outcome Type", type text}, {"Outcome Subtype", type text}, {"latitude", type number}, {"longitude", type number}, {"intake_is_dead", type text}, {"geopoint", type text}, {"intake_duration", Int64.Type}, {"is_current_month", type logical}, {"outcome_is_dead", type logical}, {"outcome_is_current", type logical}, {"outcome_is_other", type logical}, {"outcome_is_alive", type logical}, {"was_outcome_alive", Int64.Type}})
				in
				    #"Tipo Alterado"

	changedProperty = Name

	annotation PBI_ResultType = Table

